import React from "react";
import ReactDOM from "react-dom/client";
import { App } from "./App.tsx";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);


/* 

project -> better visual ping -> hub of three schools-> pick one
-> pick comparison year (2019, 2025) -> show report of changes -> email summary

deeper -> project will be called better vping -> user can pick between 3 predefined schools
-> iframe showing the current website -> comparison tool -> select year to compare
-> show 5 - 10 important changes - focus on athletes and coaches -> section with suggest email template (AI SDK)

even deeper -> project will be called visual ping
-> the initial page will be 100% filled with 3 sections, one for each predefined school and a CTA to see data about that school
-> next page iframe in the left handside showing current page (good looking iframe)
-> right handside, a list of predefined URLS to compare the current page with
-> on click compare shift the UI to two different iframes side by side (current and old), (optional with one scroll bar/action that scrolls both)
-> below the iframe display 5 - 10 differences from both pages, displaying what changed, the before and the after,
-> most differences are on staff changes, most important staff comes first -> phone number, descriptions and etc
-> a fixed section on the left handside will appear as soon as diff load with a summary and description generated by AI with loading state,
the section will remain when scrolling and a CTA "Create email" will do a mock url mailto:someone?title='123'&summary=123
*/